
a.a =  1  # efer 1 # efer

b = ''' # efer 1 # efer
# efer 1 # efer
'''   # efer 1 # efer

it = {it1 = 2}

itr."E" = {it1 = {it1 = 1, it2 = 2}, bin = ''' # efer 1 # efer
# efer 1 # efer
''', it2 = 2}  # efer 1 # efer
